### ISSUE TITLE
Allow joins of two or more TS objects

### ISSUE THREAD

**Issue by chiraganand** [xKDR/TSFrames.jl#40]
Currently, `TSx.join()` can only merge two objects `TS` objects. `DataFrames.innerjoin()` et all do support joining of two or more objects so it should be possible to replicate that behaviour in TSx join methods.

**Comment by codetalker7** [comment]
Hi @chiraganand. I'm assuming we have to use a variable number of arguments for this; something like this: 

```julia
Base.join(ts1::TSFrame, ts2::TSFrame, ts..., ::T)
```
where `T` is some join type. But the problem with the above is that `ts...` needs to be the positional argument for this to work.

A simple solution to this problem is to just do the following: instead of having the join type as the last parameter, have it as the first parameter; so something like this: 

```julia
Base.join(::T, ts1::TSFrame, ts2::TSFrame, ts...)
```
Is this okay? Should I go ahead with this, i.e put the join type argument as the first argument in all the `Base.join` methods?

**Comment by codetalker7** [comment]
Another possible solution for this was to put the join type as a keyword argument, but then we won't be able to do multiple dispatch.
